source 'http://rubygems.org'

ruby '2.2.3'

gem 'datamapper'
gem 'dm-postgres-adapter'
gem 'rspec'
gem 'rspec-sinatra'
gem 'sinatra'
gem 'capybara'
gem 'sinatra-flash'
gem 'selenium-webdriver'
gem 'database_cleaner'
gem 'rake'
gem 'rerun'
gem 'bcrypt-ruby', require: 'bcrypt'
